<?php
require_once __DIR__ . '/includes/bootstrap.php';
$pageUser = require_login($pdo);
$documentId = (int) ($_GET['id'] ?? 0);
$document = $documentId > 0 ? get_document($pdo, $documentId) : null;
if (!$document || !user_can_view_document($pdo, $pageUser, $document)) { http_response_code(404); exit('문서를 찾을 수 없습니다.'); }
$attachments = get_document_attachments($pdo, $documentId);
$steps = get_document_steps($pdo, $documentId);
?><!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($document['doc_no'] ?: '-') ?> | 인쇄용</title><style>body{font-family:Arial,"Apple SD Gothic Neo","Noto Sans KR",sans-serif;color:#111;padding:24px;}h1{margin:0 0 8px;}table{width:100%;border-collapse:collapse;margin-top:16px;}th,td{border:1px solid #bbb;padding:10px;text-align:left;font-size:14px;} .box{border:1px solid #bbb;padding:16px;margin-top:16px;white-space:pre-wrap;line-height:1.7;} .meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px;} @media print {.print-btn{display:none}}</style></head><body><button class="print-btn" onclick="window.print()">인쇄</button><h1><?= e($document['title']) ?></h1><div class="meta"><div>문서번호: <?= e($document['doc_no'] ?: '-') ?></div><div>상태: <?= e(document_status_label($document['status'])) ?></div><div>회사: <?= e($document['company_name']) ?> (<?= e($document['company_code']) ?>)</div><div>작성자: <?= e($document['writer_name']) ?> / <?= e($document['writer_job_title'] ?: '직급 미설정') ?></div><div>작성일: <?= e(format_datetime($document['created_at'])) ?></div><div>최근 수정: <?= e(format_datetime($document['updated_at'])) ?></div></div><div class="box"><?= e($document['content']) ?></div><h3>첨부파일</h3><ul><?php if ($attachments): foreach ($attachments as $file): ?><li><?= e($file['original_name']) ?></li><?php endforeach; else: ?><li>없음</li><?php endif; ?></ul><h3>결재선</h3><table><thead><tr><th>순서</th><th>결재자</th><th>상태</th><th>처리시각</th><th>의견</th></tr></thead><tbody><?php foreach ($steps as $step): ?><tr><td><?= e((string) $step['step_no']) ?>차</td><td><?= e($step['approver_name']) ?> / <?= e($step['approver_job_title'] ?: '직급 미설정') ?></td><td><?= e(step_status_label($step['status'])) ?></td><td><?= e(format_datetime($step['acted_at'])) ?></td><td><?= e($step['comment'] ?: '-') ?></td></tr><?php endforeach; ?></tbody></table></body></html>
